/******************************************************************************
 *
 * Copyright 2011 KeyPoint Technologies (UK) Ltd.   
 * All rights reserved. This program and the accompanying materials   
 * are made available under the terms of the Eclipse Public License v1.0  
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html

 *           
 * Contributors: 
 * KeyPoint Technologies (UK) Ltd - Initial API and implementation
 *
 *****************************************************************************/
/**
 * @file    kptapi_suggtypes.h
 *
 * @brief   Structures and defines for suggestion types.
 *
 * @details This file contains the suggestion types associated with
 * KPTSuggEntryT::suggestionType.
 *
 *****************************************************************************/
#if defined (_MSC_VER) && (_MSC_VER >= 1020)
#pragma once
#endif

#ifndef H_KPTAPI_SUGGTYPES_H
#define H_KPTAPI_SUGGTYPES_H

/*
 * These types are associated with KPTSuggEntryT::suggestionType.
 */

/**
 * Empty Suggestion.
 * This value is used for initialisation only.
 * @sa KPTSuggEntryT::suggestionType
 */
#define KPTSUGGSTYPE_EMPTY                  0

/**
 * General Word Suggestion.
 * Represents a normal word suggestion.
 */
#define KPTSUGGSTYPE_WORD                   1

/**
 * Elision Suggestion.
 * Represents an elision suggestion.
 */
#define KPTSUGGSTYPE_ELISION                2

/**
 * Prefix Suggestion.
 * The suggestion contains a valid prefix from the loaded dictionaries. The
 * prefix may or may not be a complete word.
 */
#define KPTSUGGSTYPE_PREFIXMATCH            6

/**
 * Content Suggestion.
 * The suggestion contains tagged content.
 */
#define KPTSUGGSTYPE_CONTENT                7

/**
 * Punctuation Suggestion.
 * The suggestion is based on the text before the cursor and a variable punctuation list.
 */
#define KPTSUGGSTYPE_PUNCTUATIONLIST        8

/**
 * Acronym Expansion.
 * The suggestion expands an acronym to its full form.
 */
#define KPTSUGGSTYPE_ACRONYMEXPANSION       9

/**
 * Error Correction.
 * The suggestion is generated by the error correction algorithms.
 */
#define KPTSUGGSTYPE_ERRORCORRECTION        10


/**
 * Space Contraction.
 * The suggestion ignores the previous space in the buffer.
 */
#define KPTSUGGSTYPE_SPACECONTRACTION       12

/**
 * Next Letter Set.
 * The suggestion text represents a set of letters that would match a valid suggestion.
 */
#define KPTSUGGSTYPE_NEXTLETTER             13


/**
 * Composition Suggestion.
 * The suggestion contains the character contained in the composition string
 */
#define KPTSUGGSTYPE_COMPOSITION            16


/**
  * Proximity Suggestions
  * This suggestion is generated by the proximity suggestion algorithm.
  */
#define KPTSUGGSTYPE_PROXIMITYSUGGESTION	17

#endif /* #ifndef H_KPTAPI_SUGGTYPES_H */
