/*
 * IDENTIFICATION:
 * stub generated Tue Aug 14 15:32:37 2012
 * with a MiG generated by bootstrap_cmds-84
 * OPTIONS: 
 */

/* Module octopus */

#define	__MIG_check__Request__octopus_subsystem__ 1

#include <string.h>
#include <mach/ndr.h>
#include <mach/boolean.h>
#include <mach/kern_return.h>
#include <mach/notify.h>
#include <mach/mach_types.h>
#include <mach/message.h>
#include <mach/mig_errors.h>
#include <mach/port.h>

#include <mach/std_types.h>
#include <mach/mig.h>
#include <mach/mig.h>
#include <mach/mach_types.h>
#include "octopus_mach_types.h"

#ifndef	mig_internal
#define	mig_internal	static __inline__
#endif	/* mig_internal */

#ifndef	mig_external
#define mig_external
#endif	/* mig_external */

#if	!defined(__MigTypeCheck) && defined(TypeCheck)
#define	__MigTypeCheck		TypeCheck	/* Legacy setting */
#endif	/* !defined(__MigTypeCheck) */

#if	!defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)
#define	__MigKernelSpecificCode	_MIG_KERNEL_SPECIFIC_CODE_	/* Legacy setting */
#endif	/* !defined(__MigKernelSpecificCode) */

#ifndef	LimitCheck
#define	LimitCheck 0
#endif	/* LimitCheck */

#ifndef	min
#define	min(a,b)  ( ((a) < (b))? (a): (b) )
#endif	/* min */

#if !defined(_WALIGN_)
#define _WALIGN_(x) (((x) + 3) & ~3)
#endif /* !defined(_WALIGN_) */

#if !defined(_WALIGNSZ_)
#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))
#endif /* !defined(_WALIGNSZ_) */

#ifndef	UseStaticTemplates
#define	UseStaticTemplates	0
#endif	/* UseStaticTemplates */

#ifndef	__DeclareRcvRpc
#define	__DeclareRcvRpc(_NUM_, _NAME_)
#endif	/* __DeclareRcvRpc */

#ifndef	__BeforeRcvRpc
#define	__BeforeRcvRpc(_NUM_, _NAME_)
#endif	/* __BeforeRcvRpc */

#ifndef	__AfterRcvRpc
#define	__AfterRcvRpc(_NUM_, _NAME_)
#endif	/* __AfterRcvRpc */

#ifndef	__DeclareRcvSimple
#define	__DeclareRcvSimple(_NUM_, _NAME_)
#endif	/* __DeclareRcvSimple */

#ifndef	__BeforeRcvSimple
#define	__BeforeRcvSimple(_NUM_, _NAME_)
#endif	/* __BeforeRcvSimple */

#ifndef	__AfterRcvSimple
#define	__AfterRcvSimple(_NUM_, _NAME_)
#endif	/* __AfterRcvSimple */

#define novalue void

#define msgh_request_port	msgh_local_port
#define MACH_MSGH_BITS_REQUEST(bits)	MACH_MSGH_BITS_LOCAL(bits)
#define msgh_reply_port		msgh_remote_port
#define MACH_MSGH_BITS_REPLY(bits)	MACH_MSGH_BITS_REMOTE(bits)

#define MIG_RETURN_ERROR(X, code)	{\
				((mig_reply_error_t *)X)->RetCode = code;\
				((mig_reply_error_t *)X)->NDR = NDR_record;\
				return;\
				}

/* typedefs for all requests */

#ifndef __Request__octopus_subsystem__defined
#define __Request__octopus_subsystem__defined

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
	} __Request__oGetStats_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		uint32_t maxSugg;
		uint32_t suggThreshold;
		bool proximitySuggestion;
		char proximitySuggestionPad[3];
		bool errorCorrection;
		char errorCorrectionPad[3];
		bool completion;
		char completionPad[3];
	} __Request__oSuggConfigure_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		bool capKnownWords;
		char capKnownWordsPad[3];
		bool capSentence;
		char capSentencePad[3];
		bool capUser;
		char capUserPad[3];
		bool capNext;
		char capNextPad[3];
	} __Request__oSuggConfigureCaps_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
	} __Request__oSuggGetSuggestions_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
	} __Request__oInputClear_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mach_msg_type_number_t strOffset; /* MiG doesn't use it */
		mach_msg_type_number_t strCnt;
		char str[257];
		char strPad[3];
		int32_t capitalize;
		bool disableLearn;
		char disableLearnPad[3];
	} __Request__oInputInsertString_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		int32_t typex;
		int32_t offset;
	} __Request__oInputCursorMove_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		int32_t before;
		int32_t after;
	} __Request__oInputRemove_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		bool autolearn;
		char autolearnPad[3];
	} __Request__oEnableAutoLearning_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		uint32_t set;
		uint32_t ident;
		bool appendSpace;
		char appendSpacePad[3];
	} __Request__oInputInsertSugg_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
	} __Request__oInputLearn_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
	} __Request__oProfileSave_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
	} __Request__oDictGetList_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		uint32_t idx;
	} __Request__oUserDictGetWordForID_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
	} __Request__oUserDictClear_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
	} __Request__oUserDictGetNumWords_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
	} __Request__oUserDictImportMessages_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
	} __Request__oUserDictImportContacts_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
	} __Request__oReloadPrefs_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif
#endif /* !__Request__octopus_subsystem__defined */

/* typedefs for all replies */

#ifndef __Reply__octopus_subsystem__defined
#define __Reply__octopus_subsystem__defined

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
		ostats_t stats;
	} __Reply__oGetStats_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__oSuggConfigure_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__oSuggConfigureCaps_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
		sSuggestions suggs;
	} __Reply__oSuggGetSuggestions_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__oInputClear_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__oInputInsertString_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__oInputCursorMove_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__oInputRemove_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__oEnableAutoLearning_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__oInputInsertSugg_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__oInputLearn_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__oProfileSave_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_ool_descriptor_t dicts;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t dictsCnt;
	} __Reply__oDictGetList_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
		mach_msg_type_number_t wordOffset; /* MiG doesn't use it */
		mach_msg_type_number_t wordCnt;
		oword_t word[1];
		char wordPad[3];
	} __Reply__oUserDictGetWordForID_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__oUserDictClear_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
		uint32_t numWords;
	} __Reply__oUserDictGetNumWords_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__oUserDictImportMessages_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__oUserDictImportContacts_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__oReloadPrefs_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif
#endif /* !__Reply__octopus_subsystem__defined */


/* union of all replies */

#ifndef __ReplyUnion__srv_octopus_subsystem__defined
#define __ReplyUnion__srv_octopus_subsystem__defined
union __ReplyUnion__srv_octopus_subsystem {
	__Reply__oGetStats_t Reply_oGetStats;
	__Reply__oSuggConfigure_t Reply_oSuggConfigure;
	__Reply__oSuggConfigureCaps_t Reply_oSuggConfigureCaps;
	__Reply__oSuggGetSuggestions_t Reply_oSuggGetSuggestions;
	__Reply__oInputClear_t Reply_oInputClear;
	__Reply__oInputInsertString_t Reply_oInputInsertString;
	__Reply__oInputCursorMove_t Reply_oInputCursorMove;
	__Reply__oInputRemove_t Reply_oInputRemove;
	__Reply__oEnableAutoLearning_t Reply_oEnableAutoLearning;
	__Reply__oInputInsertSugg_t Reply_oInputInsertSugg;
	__Reply__oInputLearn_t Reply_oInputLearn;
	__Reply__oProfileSave_t Reply_oProfileSave;
	__Reply__oDictGetList_t Reply_oDictGetList;
	__Reply__oUserDictGetWordForID_t Reply_oUserDictGetWordForID;
	__Reply__oUserDictClear_t Reply_oUserDictClear;
	__Reply__oUserDictGetNumWords_t Reply_oUserDictGetNumWords;
	__Reply__oUserDictImportMessages_t Reply_oUserDictImportMessages;
	__Reply__oUserDictImportContacts_t Reply_oUserDictImportContacts;
	__Reply__oReloadPrefs_t Reply_oReloadPrefs;
};
#endif /* __RequestUnion__srv_octopus_subsystem__defined */
/* Forward Declarations */


mig_internal novalue _XoGetStats
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XoSuggConfigure
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XoSuggConfigureCaps
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XoSuggGetSuggestions
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XoInputClear
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XoInputInsertString
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XoInputCursorMove
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XoInputRemove
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XoEnableAutoLearning
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XoInputInsertSugg
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XoInputLearn
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XoProfileSave
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XoDictGetList
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XoUserDictGetWordForID
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XoUserDictClear
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XoUserDictGetNumWords
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XoUserDictImportMessages
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XoUserDictImportContacts
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XoReloadPrefs
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);


#if ( __MigTypeCheck )
#if __MIG_check__Request__octopus_subsystem__
#if !defined(__MIG_check__Request__oGetStats_t__defined)
#define __MIG_check__Request__oGetStats_t__defined

mig_internal kern_return_t __MIG_check__Request__oGetStats_t(__attribute__((__unused__)) __Request__oGetStats_t *In0P)
{

	typedef __Request__oGetStats_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__oGetStats_t__defined) */
#endif /* __MIG_check__Request__octopus_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine oGetStats */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t srv_oGetStats
(
	mach_port_t server,
	ostats_t *stats
);

/* Routine oGetStats */
mig_internal novalue _XoGetStats
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__oGetStats_t __Request;
	typedef __Reply__oGetStats_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__oGetStats_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__oGetStats_t__defined */

	__DeclareRcvRpc(777, "oGetStats")
	__BeforeRcvRpc(777, "oGetStats")

#if	defined(__MIG_check__Request__oGetStats_t__defined)
	check_result = __MIG_check__Request__oGetStats_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__oGetStats_t__defined) */

	OutP->RetCode = srv_oGetStats(In0P->Head.msgh_request_port, &OutP->stats);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(777, "oGetStats")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__octopus_subsystem__
#if !defined(__MIG_check__Request__oSuggConfigure_t__defined)
#define __MIG_check__Request__oSuggConfigure_t__defined

mig_internal kern_return_t __MIG_check__Request__oSuggConfigure_t(__attribute__((__unused__)) __Request__oSuggConfigure_t *In0P)
{

	typedef __Request__oSuggConfigure_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__oSuggConfigure_t__defined) */
#endif /* __MIG_check__Request__octopus_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine oSuggConfigure */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t srv_oSuggConfigure
(
	mach_port_t server,
	uint32_t maxSugg,
	uint32_t suggThreshold,
	bool proximitySuggestion,
	bool errorCorrection,
	bool completion
);

/* Routine oSuggConfigure */
mig_internal novalue _XoSuggConfigure
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		uint32_t maxSugg;
		uint32_t suggThreshold;
		bool proximitySuggestion;
		char proximitySuggestionPad[3];
		bool errorCorrection;
		char errorCorrectionPad[3];
		bool completion;
		char completionPad[3];
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__oSuggConfigure_t __Request;
	typedef __Reply__oSuggConfigure_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__oSuggConfigure_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__oSuggConfigure_t__defined */

	__DeclareRcvRpc(778, "oSuggConfigure")
	__BeforeRcvRpc(778, "oSuggConfigure")

#if	defined(__MIG_check__Request__oSuggConfigure_t__defined)
	check_result = __MIG_check__Request__oSuggConfigure_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__oSuggConfigure_t__defined) */

	OutP->RetCode = srv_oSuggConfigure(In0P->Head.msgh_request_port, In0P->maxSugg, In0P->suggThreshold, In0P->proximitySuggestion, In0P->errorCorrection, In0P->completion);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(778, "oSuggConfigure")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__octopus_subsystem__
#if !defined(__MIG_check__Request__oSuggConfigureCaps_t__defined)
#define __MIG_check__Request__oSuggConfigureCaps_t__defined

mig_internal kern_return_t __MIG_check__Request__oSuggConfigureCaps_t(__attribute__((__unused__)) __Request__oSuggConfigureCaps_t *In0P)
{

	typedef __Request__oSuggConfigureCaps_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__oSuggConfigureCaps_t__defined) */
#endif /* __MIG_check__Request__octopus_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine oSuggConfigureCaps */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t srv_oSuggConfigureCaps
(
	mach_port_t server,
	bool capKnownWords,
	bool capSentence,
	bool capUser,
	bool capNext
);

/* Routine oSuggConfigureCaps */
mig_internal novalue _XoSuggConfigureCaps
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		bool capKnownWords;
		char capKnownWordsPad[3];
		bool capSentence;
		char capSentencePad[3];
		bool capUser;
		char capUserPad[3];
		bool capNext;
		char capNextPad[3];
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__oSuggConfigureCaps_t __Request;
	typedef __Reply__oSuggConfigureCaps_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__oSuggConfigureCaps_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__oSuggConfigureCaps_t__defined */

	__DeclareRcvRpc(779, "oSuggConfigureCaps")
	__BeforeRcvRpc(779, "oSuggConfigureCaps")

#if	defined(__MIG_check__Request__oSuggConfigureCaps_t__defined)
	check_result = __MIG_check__Request__oSuggConfigureCaps_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__oSuggConfigureCaps_t__defined) */

	OutP->RetCode = srv_oSuggConfigureCaps(In0P->Head.msgh_request_port, In0P->capKnownWords, In0P->capSentence, In0P->capUser, In0P->capNext);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(779, "oSuggConfigureCaps")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__octopus_subsystem__
#if !defined(__MIG_check__Request__oSuggGetSuggestions_t__defined)
#define __MIG_check__Request__oSuggGetSuggestions_t__defined

mig_internal kern_return_t __MIG_check__Request__oSuggGetSuggestions_t(__attribute__((__unused__)) __Request__oSuggGetSuggestions_t *In0P)
{

	typedef __Request__oSuggGetSuggestions_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__oSuggGetSuggestions_t__defined) */
#endif /* __MIG_check__Request__octopus_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine oSuggGetSuggestions */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t srv_oSuggGetSuggestions
(
	mach_port_t server,
	sSuggestions *suggs
);

/* Routine oSuggGetSuggestions */
mig_internal novalue _XoSuggGetSuggestions
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__oSuggGetSuggestions_t __Request;
	typedef __Reply__oSuggGetSuggestions_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__oSuggGetSuggestions_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__oSuggGetSuggestions_t__defined */

	__DeclareRcvRpc(780, "oSuggGetSuggestions")
	__BeforeRcvRpc(780, "oSuggGetSuggestions")

#if	defined(__MIG_check__Request__oSuggGetSuggestions_t__defined)
	check_result = __MIG_check__Request__oSuggGetSuggestions_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__oSuggGetSuggestions_t__defined) */

	OutP->RetCode = srv_oSuggGetSuggestions(In0P->Head.msgh_request_port, &OutP->suggs);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(780, "oSuggGetSuggestions")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__octopus_subsystem__
#if !defined(__MIG_check__Request__oInputClear_t__defined)
#define __MIG_check__Request__oInputClear_t__defined

mig_internal kern_return_t __MIG_check__Request__oInputClear_t(__attribute__((__unused__)) __Request__oInputClear_t *In0P)
{

	typedef __Request__oInputClear_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__oInputClear_t__defined) */
#endif /* __MIG_check__Request__octopus_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine oInputClear */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t srv_oInputClear
(
	mach_port_t server
);

/* Routine oInputClear */
mig_internal novalue _XoInputClear
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__oInputClear_t __Request;
	typedef __Reply__oInputClear_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__oInputClear_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__oInputClear_t__defined */

	__DeclareRcvRpc(781, "oInputClear")
	__BeforeRcvRpc(781, "oInputClear")

#if	defined(__MIG_check__Request__oInputClear_t__defined)
	check_result = __MIG_check__Request__oInputClear_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__oInputClear_t__defined) */

	OutP->RetCode = srv_oInputClear(In0P->Head.msgh_request_port);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(781, "oInputClear")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__octopus_subsystem__
#if !defined(__MIG_check__Request__oInputInsertString_t__defined)
#define __MIG_check__Request__oInputInsertString_t__defined

mig_internal kern_return_t __MIG_check__Request__oInputInsertString_t(__attribute__((__unused__)) __Request__oInputInsertString_t *In0P, __attribute__((__unused__)) __Request__oInputInsertString_t **In1PP)
{

	typedef __Request__oInputInsertString_t __Request;
	__Request *In1P;
#if	__MigTypeCheck
	unsigned int msgh_size;
#endif	/* __MigTypeCheck */
	unsigned int msgh_size_delta;

#if	__MigTypeCheck
	msgh_size = In0P->Head.msgh_size;
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 260)) ||  (msgh_size > (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if defined(__NDR_convert__int_rep__Request__oInputInsertString_t__strCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__oInputInsertString_t__strCnt(&In0P->strCnt, In0P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__oInputInsertString_t__strCnt__defined */
	msgh_size_delta = _WALIGN_(In0P->strCnt);
#if	__MigTypeCheck
	if ( In0P->strCnt > 257 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 260)) < In0P->strCnt) ||
	    (msgh_size != (mach_msg_size_t)(sizeof(__Request) - 260) + _WALIGN_(In0P->strCnt)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	*In1PP = In1P = (__Request *) ((pointer_t) In0P + msgh_size_delta - 260);

#if __MigTypeCheck
	{
		char * msg_limit = ((char *) In0P) + In0P->Head.msgh_size;
		size_t memchr_limit;

		memchr_limit = min((msg_limit - In0P->str),  257);
		if (( memchr(In0P->str, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
	}
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__oInputInsertString_t__defined) */
#endif /* __MIG_check__Request__octopus_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine oInputInsertString */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t srv_oInputInsertString
(
	mach_port_t server,
	const oword_t str,
	int32_t capitalize,
	bool disableLearn
);

/* Routine oInputInsertString */
mig_internal novalue _XoInputInsertString
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mach_msg_type_number_t strOffset; /* MiG doesn't use it */
		mach_msg_type_number_t strCnt;
		char str[257];
		char strPad[3];
		int32_t capitalize;
		bool disableLearn;
		char disableLearnPad[3];
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__oInputInsertString_t __Request;
	typedef __Reply__oInputInsertString_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Request *In1P;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__oInputInsertString_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__oInputInsertString_t__defined */

	__DeclareRcvRpc(782, "oInputInsertString")
	__BeforeRcvRpc(782, "oInputInsertString")

#if	defined(__MIG_check__Request__oInputInsertString_t__defined)
	check_result = __MIG_check__Request__oInputInsertString_t((__Request *)In0P, (__Request **)&In1P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__oInputInsertString_t__defined) */

	OutP->RetCode = srv_oInputInsertString(In0P->Head.msgh_request_port, In0P->str, In1P->capitalize, In1P->disableLearn);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(782, "oInputInsertString")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__octopus_subsystem__
#if !defined(__MIG_check__Request__oInputCursorMove_t__defined)
#define __MIG_check__Request__oInputCursorMove_t__defined

mig_internal kern_return_t __MIG_check__Request__oInputCursorMove_t(__attribute__((__unused__)) __Request__oInputCursorMove_t *In0P)
{

	typedef __Request__oInputCursorMove_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__oInputCursorMove_t__defined) */
#endif /* __MIG_check__Request__octopus_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine oInputCursorMove */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t srv_oInputCursorMove
(
	mach_port_t server,
	int32_t typex,
	int32_t offset
);

/* Routine oInputCursorMove */
mig_internal novalue _XoInputCursorMove
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		int32_t typex;
		int32_t offset;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__oInputCursorMove_t __Request;
	typedef __Reply__oInputCursorMove_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__oInputCursorMove_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__oInputCursorMove_t__defined */

	__DeclareRcvRpc(783, "oInputCursorMove")
	__BeforeRcvRpc(783, "oInputCursorMove")

#if	defined(__MIG_check__Request__oInputCursorMove_t__defined)
	check_result = __MIG_check__Request__oInputCursorMove_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__oInputCursorMove_t__defined) */

	OutP->RetCode = srv_oInputCursorMove(In0P->Head.msgh_request_port, In0P->typex, In0P->offset);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(783, "oInputCursorMove")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__octopus_subsystem__
#if !defined(__MIG_check__Request__oInputRemove_t__defined)
#define __MIG_check__Request__oInputRemove_t__defined

mig_internal kern_return_t __MIG_check__Request__oInputRemove_t(__attribute__((__unused__)) __Request__oInputRemove_t *In0P)
{

	typedef __Request__oInputRemove_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__oInputRemove_t__defined) */
#endif /* __MIG_check__Request__octopus_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine oInputRemove */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t srv_oInputRemove
(
	mach_port_t server,
	int32_t before,
	int32_t after
);

/* Routine oInputRemove */
mig_internal novalue _XoInputRemove
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		int32_t before;
		int32_t after;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__oInputRemove_t __Request;
	typedef __Reply__oInputRemove_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__oInputRemove_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__oInputRemove_t__defined */

	__DeclareRcvRpc(784, "oInputRemove")
	__BeforeRcvRpc(784, "oInputRemove")

#if	defined(__MIG_check__Request__oInputRemove_t__defined)
	check_result = __MIG_check__Request__oInputRemove_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__oInputRemove_t__defined) */

	OutP->RetCode = srv_oInputRemove(In0P->Head.msgh_request_port, In0P->before, In0P->after);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(784, "oInputRemove")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__octopus_subsystem__
#if !defined(__MIG_check__Request__oEnableAutoLearning_t__defined)
#define __MIG_check__Request__oEnableAutoLearning_t__defined

mig_internal kern_return_t __MIG_check__Request__oEnableAutoLearning_t(__attribute__((__unused__)) __Request__oEnableAutoLearning_t *In0P)
{

	typedef __Request__oEnableAutoLearning_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__oEnableAutoLearning_t__defined) */
#endif /* __MIG_check__Request__octopus_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine oEnableAutoLearning */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t srv_oEnableAutoLearning
(
	mach_port_t server,
	bool autolearn
);

/* Routine oEnableAutoLearning */
mig_internal novalue _XoEnableAutoLearning
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		bool autolearn;
		char autolearnPad[3];
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__oEnableAutoLearning_t __Request;
	typedef __Reply__oEnableAutoLearning_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__oEnableAutoLearning_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__oEnableAutoLearning_t__defined */

	__DeclareRcvRpc(785, "oEnableAutoLearning")
	__BeforeRcvRpc(785, "oEnableAutoLearning")

#if	defined(__MIG_check__Request__oEnableAutoLearning_t__defined)
	check_result = __MIG_check__Request__oEnableAutoLearning_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__oEnableAutoLearning_t__defined) */

	OutP->RetCode = srv_oEnableAutoLearning(In0P->Head.msgh_request_port, In0P->autolearn);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(785, "oEnableAutoLearning")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__octopus_subsystem__
#if !defined(__MIG_check__Request__oInputInsertSugg_t__defined)
#define __MIG_check__Request__oInputInsertSugg_t__defined

mig_internal kern_return_t __MIG_check__Request__oInputInsertSugg_t(__attribute__((__unused__)) __Request__oInputInsertSugg_t *In0P)
{

	typedef __Request__oInputInsertSugg_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__oInputInsertSugg_t__defined) */
#endif /* __MIG_check__Request__octopus_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine oInputInsertSugg */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t srv_oInputInsertSugg
(
	mach_port_t server,
	uint32_t set,
	uint32_t ident,
	bool appendSpace
);

/* Routine oInputInsertSugg */
mig_internal novalue _XoInputInsertSugg
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		uint32_t set;
		uint32_t ident;
		bool appendSpace;
		char appendSpacePad[3];
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__oInputInsertSugg_t __Request;
	typedef __Reply__oInputInsertSugg_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__oInputInsertSugg_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__oInputInsertSugg_t__defined */

	__DeclareRcvRpc(786, "oInputInsertSugg")
	__BeforeRcvRpc(786, "oInputInsertSugg")

#if	defined(__MIG_check__Request__oInputInsertSugg_t__defined)
	check_result = __MIG_check__Request__oInputInsertSugg_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__oInputInsertSugg_t__defined) */

	OutP->RetCode = srv_oInputInsertSugg(In0P->Head.msgh_request_port, In0P->set, In0P->ident, In0P->appendSpace);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(786, "oInputInsertSugg")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__octopus_subsystem__
#if !defined(__MIG_check__Request__oInputLearn_t__defined)
#define __MIG_check__Request__oInputLearn_t__defined

mig_internal kern_return_t __MIG_check__Request__oInputLearn_t(__attribute__((__unused__)) __Request__oInputLearn_t *In0P)
{

	typedef __Request__oInputLearn_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__oInputLearn_t__defined) */
#endif /* __MIG_check__Request__octopus_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine oInputLearn */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t srv_oInputLearn
(
	mach_port_t server
);

/* Routine oInputLearn */
mig_internal novalue _XoInputLearn
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__oInputLearn_t __Request;
	typedef __Reply__oInputLearn_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__oInputLearn_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__oInputLearn_t__defined */

	__DeclareRcvRpc(787, "oInputLearn")
	__BeforeRcvRpc(787, "oInputLearn")

#if	defined(__MIG_check__Request__oInputLearn_t__defined)
	check_result = __MIG_check__Request__oInputLearn_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__oInputLearn_t__defined) */

	OutP->RetCode = srv_oInputLearn(In0P->Head.msgh_request_port);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(787, "oInputLearn")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__octopus_subsystem__
#if !defined(__MIG_check__Request__oProfileSave_t__defined)
#define __MIG_check__Request__oProfileSave_t__defined

mig_internal kern_return_t __MIG_check__Request__oProfileSave_t(__attribute__((__unused__)) __Request__oProfileSave_t *In0P)
{

	typedef __Request__oProfileSave_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__oProfileSave_t__defined) */
#endif /* __MIG_check__Request__octopus_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine oProfileSave */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t srv_oProfileSave
(
	mach_port_t server
);

/* Routine oProfileSave */
mig_internal novalue _XoProfileSave
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__oProfileSave_t __Request;
	typedef __Reply__oProfileSave_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__oProfileSave_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__oProfileSave_t__defined */

	__DeclareRcvRpc(788, "oProfileSave")
	__BeforeRcvRpc(788, "oProfileSave")

#if	defined(__MIG_check__Request__oProfileSave_t__defined)
	check_result = __MIG_check__Request__oProfileSave_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__oProfileSave_t__defined) */

	OutP->RetCode = srv_oProfileSave(In0P->Head.msgh_request_port);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(788, "oProfileSave")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__octopus_subsystem__
#if !defined(__MIG_check__Request__oDictGetList_t__defined)
#define __MIG_check__Request__oDictGetList_t__defined

mig_internal kern_return_t __MIG_check__Request__oDictGetList_t(__attribute__((__unused__)) __Request__oDictGetList_t *In0P)
{

	typedef __Request__oDictGetList_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__oDictGetList_t__defined) */
#endif /* __MIG_check__Request__octopus_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine oDictGetList */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t srv_oDictGetList
(
	mach_port_t server,
	sDictionaryArray *dicts,
	mach_msg_type_number_t *dictsCnt
);

/* Routine oDictGetList */
mig_internal novalue _XoDictGetList
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__oDictGetList_t __Request;
	typedef __Reply__oDictGetList_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__oDictGetList_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__oDictGetList_t__defined */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t dictsTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		TRUE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(789, "oDictGetList")
	__BeforeRcvRpc(789, "oDictGetList")

#if	defined(__MIG_check__Request__oDictGetList_t__defined)
	check_result = __MIG_check__Request__oDictGetList_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__oDictGetList_t__defined) */

#if	UseStaticTemplates
	OutP->dicts = dictsTemplate;
#else	/* UseStaticTemplates */
	OutP->dicts.deallocate =  TRUE;
	OutP->dicts.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->dicts.type = MACH_MSG_OOL_DESCRIPTOR;
#endif	/* UseStaticTemplates */


	RetCode = srv_oDictGetList(In0P->Head.msgh_request_port, (sDictionaryArray *)&(OutP->dicts.address), &OutP->dictsCnt);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}
	OutP->dicts.size = OutP->dictsCnt * 2062;


	OutP->NDR = NDR_record;


	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(789, "oDictGetList")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__octopus_subsystem__
#if !defined(__MIG_check__Request__oUserDictGetWordForID_t__defined)
#define __MIG_check__Request__oUserDictGetWordForID_t__defined

mig_internal kern_return_t __MIG_check__Request__oUserDictGetWordForID_t(__attribute__((__unused__)) __Request__oUserDictGetWordForID_t *In0P)
{

	typedef __Request__oUserDictGetWordForID_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__oUserDictGetWordForID_t__defined) */
#endif /* __MIG_check__Request__octopus_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine oUserDictGetWordForID */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t srv_oUserDictGetWordForID
(
	mach_port_t server,
	uint32_t idx,
	oword_t_ptr word
);

/* Routine oUserDictGetWordForID */
mig_internal novalue _XoUserDictGetWordForID
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		uint32_t idx;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__oUserDictGetWordForID_t __Request;
	typedef __Reply__oUserDictGetWordForID_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__oUserDictGetWordForID_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__oUserDictGetWordForID_t__defined */

	__DeclareRcvRpc(790, "oUserDictGetWordForID")
	__BeforeRcvRpc(790, "oUserDictGetWordForID")

#if	defined(__MIG_check__Request__oUserDictGetWordForID_t__defined)
	check_result = __MIG_check__Request__oUserDictGetWordForID_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__oUserDictGetWordForID_t__defined) */

	OutP->RetCode = srv_oUserDictGetWordForID(In0P->Head.msgh_request_port, In0P->idx, OutP->word);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;

#ifdef __LP64__
	{
		size_t strLength = strlen(OutP->word) + 1;
		if (strLength > 0xffffffff)
			MIG_RETURN_ERROR(OutP, MIG_BAD_ARGUMENTS);
		OutP->wordCnt = (mach_msg_type_number_t) strLength;
	}
#else
	OutP->wordCnt = (mach_msg_type_number_t) strlen(OutP->word) + 1;
#endif /* __LP64__ */
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply) - 260) + (_WALIGN_((257 * OutP->wordCnt + 3) & ~3));

	__AfterRcvRpc(790, "oUserDictGetWordForID")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__octopus_subsystem__
#if !defined(__MIG_check__Request__oUserDictClear_t__defined)
#define __MIG_check__Request__oUserDictClear_t__defined

mig_internal kern_return_t __MIG_check__Request__oUserDictClear_t(__attribute__((__unused__)) __Request__oUserDictClear_t *In0P)
{

	typedef __Request__oUserDictClear_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__oUserDictClear_t__defined) */
#endif /* __MIG_check__Request__octopus_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine oUserDictClear */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t srv_oUserDictClear
(
	mach_port_t server
);

/* Routine oUserDictClear */
mig_internal novalue _XoUserDictClear
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__oUserDictClear_t __Request;
	typedef __Reply__oUserDictClear_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__oUserDictClear_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__oUserDictClear_t__defined */

	__DeclareRcvRpc(791, "oUserDictClear")
	__BeforeRcvRpc(791, "oUserDictClear")

#if	defined(__MIG_check__Request__oUserDictClear_t__defined)
	check_result = __MIG_check__Request__oUserDictClear_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__oUserDictClear_t__defined) */

	OutP->RetCode = srv_oUserDictClear(In0P->Head.msgh_request_port);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(791, "oUserDictClear")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__octopus_subsystem__
#if !defined(__MIG_check__Request__oUserDictGetNumWords_t__defined)
#define __MIG_check__Request__oUserDictGetNumWords_t__defined

mig_internal kern_return_t __MIG_check__Request__oUserDictGetNumWords_t(__attribute__((__unused__)) __Request__oUserDictGetNumWords_t *In0P)
{

	typedef __Request__oUserDictGetNumWords_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__oUserDictGetNumWords_t__defined) */
#endif /* __MIG_check__Request__octopus_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine oUserDictGetNumWords */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t srv_oUserDictGetNumWords
(
	mach_port_t server,
	uint32_t *numWords
);

/* Routine oUserDictGetNumWords */
mig_internal novalue _XoUserDictGetNumWords
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__oUserDictGetNumWords_t __Request;
	typedef __Reply__oUserDictGetNumWords_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__oUserDictGetNumWords_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__oUserDictGetNumWords_t__defined */

	__DeclareRcvRpc(792, "oUserDictGetNumWords")
	__BeforeRcvRpc(792, "oUserDictGetNumWords")

#if	defined(__MIG_check__Request__oUserDictGetNumWords_t__defined)
	check_result = __MIG_check__Request__oUserDictGetNumWords_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__oUserDictGetNumWords_t__defined) */

	OutP->RetCode = srv_oUserDictGetNumWords(In0P->Head.msgh_request_port, &OutP->numWords);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(792, "oUserDictGetNumWords")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__octopus_subsystem__
#if !defined(__MIG_check__Request__oUserDictImportMessages_t__defined)
#define __MIG_check__Request__oUserDictImportMessages_t__defined

mig_internal kern_return_t __MIG_check__Request__oUserDictImportMessages_t(__attribute__((__unused__)) __Request__oUserDictImportMessages_t *In0P)
{

	typedef __Request__oUserDictImportMessages_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__oUserDictImportMessages_t__defined) */
#endif /* __MIG_check__Request__octopus_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine oUserDictImportMessages */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t srv_oUserDictImportMessages
(
	mach_port_t server
);

/* Routine oUserDictImportMessages */
mig_internal novalue _XoUserDictImportMessages
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__oUserDictImportMessages_t __Request;
	typedef __Reply__oUserDictImportMessages_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__oUserDictImportMessages_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__oUserDictImportMessages_t__defined */

	__DeclareRcvRpc(793, "oUserDictImportMessages")
	__BeforeRcvRpc(793, "oUserDictImportMessages")

#if	defined(__MIG_check__Request__oUserDictImportMessages_t__defined)
	check_result = __MIG_check__Request__oUserDictImportMessages_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__oUserDictImportMessages_t__defined) */

	OutP->RetCode = srv_oUserDictImportMessages(In0P->Head.msgh_request_port);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(793, "oUserDictImportMessages")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__octopus_subsystem__
#if !defined(__MIG_check__Request__oUserDictImportContacts_t__defined)
#define __MIG_check__Request__oUserDictImportContacts_t__defined

mig_internal kern_return_t __MIG_check__Request__oUserDictImportContacts_t(__attribute__((__unused__)) __Request__oUserDictImportContacts_t *In0P)
{

	typedef __Request__oUserDictImportContacts_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__oUserDictImportContacts_t__defined) */
#endif /* __MIG_check__Request__octopus_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine oUserDictImportContacts */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t srv_oUserDictImportContacts
(
	mach_port_t server
);

/* Routine oUserDictImportContacts */
mig_internal novalue _XoUserDictImportContacts
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__oUserDictImportContacts_t __Request;
	typedef __Reply__oUserDictImportContacts_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__oUserDictImportContacts_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__oUserDictImportContacts_t__defined */

	__DeclareRcvRpc(794, "oUserDictImportContacts")
	__BeforeRcvRpc(794, "oUserDictImportContacts")

#if	defined(__MIG_check__Request__oUserDictImportContacts_t__defined)
	check_result = __MIG_check__Request__oUserDictImportContacts_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__oUserDictImportContacts_t__defined) */

	OutP->RetCode = srv_oUserDictImportContacts(In0P->Head.msgh_request_port);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(794, "oUserDictImportContacts")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__octopus_subsystem__
#if !defined(__MIG_check__Request__oReloadPrefs_t__defined)
#define __MIG_check__Request__oReloadPrefs_t__defined

mig_internal kern_return_t __MIG_check__Request__oReloadPrefs_t(__attribute__((__unused__)) __Request__oReloadPrefs_t *In0P)
{

	typedef __Request__oReloadPrefs_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__oReloadPrefs_t__defined) */
#endif /* __MIG_check__Request__octopus_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine oReloadPrefs */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t srv_oReloadPrefs
(
	mach_port_t server
);

/* Routine oReloadPrefs */
mig_internal novalue _XoReloadPrefs
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__oReloadPrefs_t __Request;
	typedef __Reply__oReloadPrefs_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__oReloadPrefs_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__oReloadPrefs_t__defined */

	__DeclareRcvRpc(795, "oReloadPrefs")
	__BeforeRcvRpc(795, "oReloadPrefs")

#if	defined(__MIG_check__Request__oReloadPrefs_t__defined)
	check_result = __MIG_check__Request__oReloadPrefs_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__oReloadPrefs_t__defined) */

	OutP->RetCode = srv_oReloadPrefs(In0P->Head.msgh_request_port);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(795, "oReloadPrefs")
}


#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
boolean_t octopus_server(
		mach_msg_header_t *InHeadP,
		mach_msg_header_t *OutHeadP);

#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
mig_routine_t octopus_server_routine(
		mach_msg_header_t *InHeadP);


/* Description of this subsystem, for use in direct RPC */
const struct srv_octopus_subsystem {
	mig_server_routine_t 	server;	/* Server routine */
	mach_msg_id_t	start;	/* Min routine number */
	mach_msg_id_t	end;	/* Max routine number + 1 */
	unsigned int	maxsize;	/* Max msg size */
	vm_address_t	reserved;	/* Reserved */
	struct routine_descriptor	/*Array of routine descriptors */
		routine[19];
} srv_octopus_subsystem = {
	octopus_server_routine,
	777,
	796,
	(mach_msg_size_t)sizeof(union __ReplyUnion__srv_octopus_subsystem),
	(vm_address_t)0,
	{
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XoGetStats, 2, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__oGetStats_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XoSuggConfigure, 6, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__oSuggConfigure_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XoSuggConfigureCaps, 5, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__oSuggConfigureCaps_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XoSuggGetSuggestions, 2, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__oSuggGetSuggestions_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XoInputClear, 1, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__oInputClear_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XoInputInsertString, 4, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__oInputInsertString_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XoInputCursorMove, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__oInputCursorMove_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XoInputRemove, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__oInputRemove_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XoEnableAutoLearning, 2, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__oEnableAutoLearning_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XoInputInsertSugg, 4, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__oInputInsertSugg_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XoInputLearn, 1, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__oInputLearn_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XoProfileSave, 1, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__oProfileSave_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XoDictGetList, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__oDictGetList_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XoUserDictGetWordForID, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__oUserDictGetWordForID_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XoUserDictClear, 1, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__oUserDictClear_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XoUserDictGetNumWords, 2, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__oUserDictGetNumWords_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XoUserDictImportMessages, 1, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__oUserDictImportMessages_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XoUserDictImportContacts, 1, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__oUserDictImportContacts_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XoReloadPrefs, 1, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__oReloadPrefs_t)},
	}
};

mig_external boolean_t octopus_server
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	register mig_routine_t routine;

	OutHeadP->msgh_bits = MACH_MSGH_BITS(MACH_MSGH_BITS_REPLY(InHeadP->msgh_bits), 0);
	OutHeadP->msgh_remote_port = InHeadP->msgh_reply_port;
	/* Minimal size: routine() will update it if different */
	OutHeadP->msgh_size = (mach_msg_size_t)sizeof(mig_reply_error_t);
	OutHeadP->msgh_local_port = MACH_PORT_NULL;
	OutHeadP->msgh_id = InHeadP->msgh_id + 100;

	if ((InHeadP->msgh_id > 795) || (InHeadP->msgh_id < 777) ||
	    ((routine = srv_octopus_subsystem.routine[InHeadP->msgh_id - 777].stub_routine) == 0)) {
		((mig_reply_error_t *)OutHeadP)->NDR = NDR_record;
		((mig_reply_error_t *)OutHeadP)->RetCode = MIG_BAD_ID;
		return FALSE;
	}
	(*routine) (InHeadP, OutHeadP);
	return TRUE;
}

mig_external mig_routine_t octopus_server_routine
	(mach_msg_header_t *InHeadP)
{
	register int msgh_id;

	msgh_id = InHeadP->msgh_id - 777;

	if ((msgh_id > 18) || (msgh_id < 0))
		return 0;

	return srv_octopus_subsystem.routine[msgh_id].stub_routine;
}
